config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#home', as: 'root'

  # sessions
  get '/about', to: 'welcome#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  # resources :family_people
  resources :families
  resources :people
  get '/people/person_search', to: 'people#search', as: 'person_search'
  # get '/people/:id/sitters/new', to: 'people#new_sitter', as: 'new_sitter'
  # post '/people/sitters', to: 'people#create_sitter', as: 'create_sitter'

  #search path to find families
  get '/family_people/search', to: 'family_people#search', as: 'family_people_search'

  #create new family person
  get '/family_people/new', to: 'family_people#new', as: 'new_family_person'
  post '/family_people', to: 'family_people#create', as: 'family_people_create'
  post '/family_people/sitters', to: 'family_people#sitter_create', as: 'family_people_sitter_create'

end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  has_many :family_people
  has_many :families, through: :family_people
  validates :email, uniqueness: true, presence: true
  
  def self.confirm params
    @person = Person.find_by({email: params[:email]})
    @person ? @person.authenticate(params[:password]) : false
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [ :edit, :update, :destroy]

  def index
  end

  def show
    @person_family_id = -1
    @family_people = Person.find_by_id(params[:id])
    @person = Person.find_by_id(params[:id])
    if current_person
      person_family = FamilyPerson.select{ |fp| fp.role == "caregivers" && fp.person_id == current_person.id }.first()
      if person_family
        @person_family_id = person_family.family_id
      end
    end
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find_by(params[:id])
  end

  def create
    @person = Person.new(person_params)

      if @person.save
        login(@person)
        flash[:notice] = 'Your profile was successfully created.'
        redirect_to @person
      else
        flash[:notice] = 'Something went wrong. Please try again.'
        redirect_to new_person_path
    end
  end

  def update
    @person = Person.find_by(params[:id])
    if @person.update(person_params)
    redirect_to person_path(@person), notice: 'Your profile was successfully updated.'
    else
      redirect_to edit_person_path
    end
  end

  def destroy
    @person.destroy
    flash[:notice] = 'We are sorry to see you go. Your profile was successfully destroyed.'
    redirect_to root_path
  end

  private

    def set_person
      @person = Person.find_by(params[:id])
    end

    def person_params
      params.require(:person).permit(:first_name, :last_name, :phone_number, :city, :email, :password)
    end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid form-container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <strong><%= f.label :first_name %></strong>
        <%= f.text_field :first_name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <stong><%= f.label :last_name %><strong>
        <%= f.text_field :last_name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <strong><%= f.label :phone_number %></strong>
        <%= f.text_field :phone_number %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <strong><%= f.label :city %></strong>
        <%= f.text_field :city %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <strong><%= f.label :email %></strong>
        <%= f.text_field :email %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="field">
        <strong><%= f.label :password %></strong>
        <%= f.password_field :password %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
      <div class="actions">
        <%= f.submit "Sign Up", class: "btn btn-default btn-submit" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/people/new.html.erb
<div class="container-fluid">
  <div class="row welcome-header clearfix">
    <div class="col-lg-6 col-sm-12" id="sitter-swap-logo">
      <h1>SitterSwap</h1>
    </div>
    <div class="col-lg-6 col-sm-12" id="welcome-header-links">
      <%= link_to 'Log In', login_path %>
      <%= link_to 'Join', new_person_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Home', root_path %>
    </div>
  </div>
</div>
<div class="container-fluid form-container">
  <div class="log-in-header login-header-title">
    <h1>Join SitterSwap</h1>
  </div>
</div>
<%= render 'form', person: @person %>

app/views/people/show.html.erb
<div class="container-fluid">
  <div class="row welcome-header clearfix">
    <div class="col-lg-6 col-sm-12" id="sitter-swap-logo">
      <h1>SitterSwap</h1>
    </div>
    <div class="col-lg-6 col-sm-12" id="welcome-header-links">
      <%= link_to 'Log Out', logout_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Home', root_path %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 user-welcome">
      <center><h2 class="welcome-person">Welcome <%= @person.first_name %> <%= @person.last_name %></h2></center>
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="beige-header">
          <h3><strong>My Family</strong></h3>
        </div>
        <div class"col-lg-6 col-sm-12">
          <ul class="profile-relationships">
            <% Family.joins(:family_people).where('family_people.person_id': @person.id).where('family_people.role': "caregivers").each do |family| %>
              <li><strong>Family Name: </strong><%= link_to family.family_name, '/families/' + family.id.to_s %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-lg-6 col-sm-12 family-person-directions">
          <!-- how to create new family -->
          <li><strong>FIRST:</strong> Create a profile for your family. Start here: <%= link_to 'New Family', new_family_path %></li>
          <!-- how to link to a family -->
          <li><strong>NEXT:</strong> Make sure you link to your new family profile. Click here: <%= link_to 'Select Family', family_people_search_path %></li>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="beige-header">
          <h3><strong>My Sitters</strong></h3>
        </div>
        <div class="col-lg-6 col-sm-12">
          <ul class="profile-relationships">
            <% Person.joins(:family_people).where('family_people.family_id': @person_family_id).where('family_people.role': "sitters").each do |person| %>
              <li><strong>Sitter: </strong><%= link_to person.first_name, '/people/' + person.id.to_s %> | <%= mail_to person.email do %><strong>Email:</strong> <span><%= person.email %></span></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="col-lg-6 col-sm-12 family-person-directions">
          <!-- how to link to sitters -->
          <li><strong>DON'T FORGET THE SITTERS:</strong> Search for your sitter by their email address and connect! <%= link_to 'Find Your Sitters', family_people_search_path %></li>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="beige-header">
          <h3><strong>My Friends</strong></h3>
        </div>
        <div class="col-lg-6 col-sm-12">
            <ul class="profile-relationships">
              <% Family.joins(:family_people).where('family_people.person_id': @person.id).where('family_people.role': "friends").each do |family| %>
                <li><strong>Family: </strong><%= link_to family.family_name, '/families/' + family.id.to_s %></li>
              </ul>
            <% end %>
        </div>
        <div class="col-lg-6 col-sm-12 family-person-directions">
          <!-- how to link to other families -->
          <li><strong>THEN:</strong> Connect with your friends on our search page. (Make sure you know the family name they used.) <%= link_to 'Find Friend', family_people_search_path %></li>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="my-profile-section">
  <div id="my-family-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <center><h2>My Profile</h2></center>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-sm-12">
          <center>
            <p>
              <strong>Name:</strong>
              <%= @person.first_name %> <%= @person.last_name %>
            </p>
            <p>
              <strong>Phone number:</strong>
              <%= @person.phone_number %>
            </p>
            <p>
              <strong>City:</strong>
              <%= @person.city %>
            </p>
            <p>
              <strong>Email:</strong>
              <%= @person.email %>
            </p>
          </center>
        </div>
      </div>
    </div>
  </div>
</section>