config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#home', as: 'root'

  # sessions
  get '/about', to: 'welcome#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  # resources :family_people
  resources :families
  resources :people
  get '/people/person_search', to: 'people#search', as: 'person_search'
  # get '/people/:id/sitters/new', to: 'people#new_sitter', as: 'new_sitter'
  # post '/people/sitters', to: 'people#create_sitter', as: 'create_sitter'

  #search path to find families
  get '/family_people/search', to: 'family_people#search', as: 'family_people_search'

  #create new family person
  get '/family_people/new', to: 'family_people#new', as: 'new_family_person'
  post '/family_people', to: 'family_people#create', as: 'family_people_create'
  post '/family_people/sitters', to: 'family_people#sitter_create', as: 'family_people_sitter_create'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="container-fluid">
  <div class="row welcome-header clearfix">
    <div class="col-lg-6 col-sm-12" id="sitter-swap-logo">
      <h1>SitterSwap</h1>
    </div>
    <div class="col-lg-6 col-sm-12" id="welcome-header-links">
      <%= link_to 'About', about_path %>
      <%= link_to 'Join', new_person_path %>
      <%= link_to 'Log In', login_path %>
      <%= link_to 'Home', root_path %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <h2><center>The best sitter is one that's been tested by a trusted friend.</center></h2>
    <div class="about-image">
      <center><%= image_tag("http://i.imgur.com/7b0iz6H.jpg?1", class: "about-image", alt: "sitter-swap-connects-families") %></center>
    <h2>Why SitterSwap?</h2>
    <p>There are lots of options out there if you want to wade through profile after profile of potential sitters. But those large, inpersonal child care websites mean you lose time interviewing a series of strangers who may or may not turn out to be great sitters.</p>
    <p>SitterSwap lets families connect to find the best child care for their little ones. It takes away the guessing game about who a sitter is and expands your pool of child care options.</p>
  </div>
</div>
<div class="container-fluid">
  <div class="row how-it-works clearfix">
    <div class="col-md-6 col-sm-12">
      <h2>How It Works</h2>
      <p>For Parents:</p>
      <ul>
        <li>Join SitterSwap.</li>
        <li>Create a family profile.</li>
        <li>List your sitters.</li>
        <li>Link to your friends.</li>
        <li>Contact your friends' sitters too.</li>
      </ul>
      <p>It's that easy!</p>
      <p>For Sitters:</p>
      <ul>
        <li>Join SitterSwap.</li>
        <li>Connect to the families you work with.</li>
        <li>Those families and their friends can email you about a job anytime.</li>
      </ul>
      <p>You'll get more work and great references!</p>
    </div>
    <div class="col-md-6 col-sm-12" id="how-it-works-img">
      <%= image_tag("http://i.imgur.com/VxoZQqP.jpg?2", class: "chalk-image", alt: "sitter-swap-connects-families") %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row welcome-header">
    <div class="col-sm-12" id="welcome-header-links">
      <%= link_to 'Join', new_person_path %>
      <%= link_to 'Log In', login_path %>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="container-fluid">
  <div class="row welcome-header clearfix">
    <div class="col-lg-6 col-sm-12" id="sitter-swap-logo">
      <h1>SitterSwap</h1>
    </div>
    <div class="col-lg-6 col-sm-12" id="welcome-header-links">
      <%= link_to 'About', about_path %>
      <%= link_to 'Join', new_person_path %>
      <%= link_to 'Log In', login_path %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 col-sm-12">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="about-image">
        <center><%= image_tag("http://i.imgur.com/XmsjQeP.jpg?2", class: "about-image", alt: "sitter-swap-connects-families") %></center>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row sitter-swap-tagline">
    <div class="col-sm-12">
      <h2><center>Connecting Families With Trusted Child Care</center></h2>
    </div>
  </div>
</div>