config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#home', as: 'root'

  # sessions
  get '/about', to: 'welcome#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  # resources :family_people
  resources :families
  resources :people
  get '/people/person_search', to: 'people#search', as: 'person_search'
  # get '/people/:id/sitters/new', to: 'people#new_sitter', as: 'new_sitter'
  # post '/people/sitters', to: 'people#create_sitter', as: 'create_sitter'

  #search path to find families
  get '/family_people/search', to: 'family_people#search', as: 'family_people_search'

  #create new family person
  get '/family_people/new', to: 'family_people#new', as: 'new_family_person'
  post '/family_people', to: 'family_people#create', as: 'family_people_create'
  post '/family_people/sitters', to: 'family_people#sitter_create', as: 'family_people_sitter_create'

end

app/controllers/family_people_controller.rb
class FamilyPeopleController < ApplicationController
  before_action :set_family, only: [:new, :show, :edit, :update, :destroy]

  def index
    @family_people = FamilyPerson.all
  end

  def show
  end

  def new
    @family_person = FamilyPerson.new
    family_id = Family.find_by(params[:id])
  end

  def edit
  end

  def create
    @family_person = FamilyPerson.new(family_person_create_params)
    @family_person.person_id = current_person.id
    @results = Family.find_by(params[:id])

      if @family_person.save
        flash[:notice] = "Your family has been confirmed."
        redirect_to '/people/' + current_person.id.to_s
      else
        flash[:error] = "Something went wrong. Please try again."
        redirect_to family_people_search_path
      end
  end

  def sitter_create
    @family_person = FamilyPerson.new(family_person_sitter_create_params)
    fams = FamilyPerson.select{ |fp| fp.role == "caregivers" && fp.person_id == current_person.id }

    if fams
      @family_person.family_id = fams[0].family_id
    end
    cur_fams = FamilyPerson.select{ |fp| fp.role == @family_person.role && fp.person_id == @family_person.person_id && fp.family_id == @family_person.family_id }

    if @family_person.save
      flash[:notice] = "Your sitter has been confirmed."
      flash[:color] = "success"
      redirect_to '/people/' + current_person.id.to_s
    else
      flash[:error] = "Something went wrong. Please try again."
      flash[:color] = "failure"
      redirect_to family_people_search
    end
  end

  def update
    respond_to do |format|
      if @family_person.update(family_person_params)
        format.html { redirect_to @family_person, notice: 'Family person was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_person }
      else
        format.html { render :edit }
        format.json { render json: @family_person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @family_person.destroy
    respond_to do |format|
      format.html { redirect_to family_people_url, notice: 'Family person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @user_input = params[:q]
    @results = Family.all.select{|fam| fam.family_name == @user_input}
    @sitters = Person.all.select{|person| person.email == @user_input}
  end

  private

    def set_family
      @family = Family.all.select{|fam| fam.id == (params[:id])}
    end

    def family_person_params
      params.require(:family_person).permit(:role, :family_id, :person_id)
    end

    def family_person_create_params
      params.permit(:role, :family_id, :person_id)
    end

    def family_person_sitter_create_params
      params.permit(:role, :family_id, :person_id)
    end

end

app/helpers/family_people_helper.rb
module FamilyPeopleHelper
end

app/views/family_people/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Family People Index</h2>

app/views/family_people/search.html.erb
<div class="container-fluid">
  <div class="row welcome-header clearfix">
    <div class="col-lg-6 col-sm-12" id="sitter-swap-logo">
      <h1>SitterSwap</h1>
    </div>
    <div class="col-lg-6 col-sm-12" id="welcome-header-links">
      <%= link_to 'Log Out', logout_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Profile', person_path(current_person) %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row search-page-header">
    <div class="col-sm-12">
      <center>
        <h1>Search Page</h1>
        <p class="search-tagline">Find the families &amp people that make SitterSwap so great!</p>
      </center>
    </div>
  </div>
</div>
<!-- search and results to select a caregivers family -->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <h1>Family Search <span class="small-header">(Scroll down to search for a sitter)</span></h1>
      <p>Search by the <i>family name</i>, usually the surname.</p>
      <p>For example, Doe for John Doe.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 search-bar">
      <%= form_tag("/family_people/search", method: "get") do %>
        <%= label_tag(:q, "Search for a family") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <p>Search Results:</p>
      <hr>
      <ul>
        <% @results.each do |result| %>
          <li>
            <p><%= link_to result.family_name, '/families/' + result.id.to_s, role: "caregivers" %><p>
            <div class="actions">
              <%= button_to "Parent", family_people_create_path, params: {role: "caregivers", family_id: result.id}, form_class: "new-thing", class: "btn btn-default btn-search" %>
            </div>
            <div class="actions">
              <%= button_to "Friend", family_people_create_path, params: {role: "friends", family_id: result.id}, form_class: "new-thing", class: "btn btn-default btn-search" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>Sitter Search</h1>
      <p>Search for a person by <i>email</i>.</p>
      <p>For example, name@example.com.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 search-bar">
      <%= form_tag("/family_people/search", method: "get") do %>
        <%= label_tag(:q, "Search for a person") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <p>Search Results:</p>
      <hr>
      <ul>
        <% @sitters.each do |sitter| %>
          <li>
            <p><%= link_to sitter.first_name + " " + sitter.last_name, '/people/' + sitter.id.to_s %></p>
            <div class="actions">
              <%= button_to "Confirm Sitter", family_people_sitter_create_path, params: {role: "sitters", person_id: sitter.id}, form_class: "new-thing", class: "btn btn-default btn-search" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
</div>